# Generated by Django 6.0.5 on 2026-05-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP'), ('UTILITY', 'UTILITY'), ('TRAVEL', 'TRAVEL')], max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('normalized_unit', models.CharField(default='kgCO2e', max_length=50)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('FAILED', 'FAILED')], default='PENDING', max_length=20)),
                ('suspicious', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
